In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("Groceries_Sales_data.xlsx")

In [3]:
df

          Date    Sales
0   2018-02-01  21199.0
1   2018-02-02  10634.0
2   2018-02-03   7966.0
3   2018-02-04   1353.0
4   2018-02-05   9497.0
..         ...      ...
751 2020-02-22  18723.1
752 2020-02-23   4274.9
753 2020-02-24  45805.7
754 2020-02-25  35566.3
755 2020-02-26  46703.0

[756 rows x 2 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    756 non-null    datetime64[us]
 1   Sales   756 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 11.9 KB

In [6]:
df.sort_values(by='Date', ascending=False)

          Date    Sales
755 2020-02-26  46703.0
754 2020-02-25  35566.3
753 2020-02-24  45805.7
752 2020-02-23   4274.9
751 2020-02-22  18723.1
..         ...      ...
4   2018-02-05   9497.0
3   2018-02-04   1353.0
2   2018-02-03   7966.0
1   2018-02-02  10634.0
0   2018-02-01  21199.0

[756 rows x 2 columns]

In [14]:
def pareto_analysis(df, sort_by, n):
    df_order = df.sort_values(by=sort_by, ascending=False).copy()
    ranks = df_order[sort_by].rank(method='first', ascending=False)
    df_order['group'] = pd.qcut(ranks, q=n)
    total = df_order[sort_by].sum()
    proportions = df_order.groupby('group')[sort_by].sum()/total
    proportions = proportions.sort_values(ascending=False)
    return proportions

In [15]:
pareto_analysis(df=df, sort_by='Sales', n=10)

group
(0.999, 76.5]     0.283446
(76.5, 152.0]     0.197281
(152.0, 227.5]    0.135945
(227.5, 303.0]    0.104702
(303.0, 378.5]    0.081238
(378.5, 454.0]    0.067009
(454.0, 529.5]    0.051118
(529.5, 605.0]    0.040113
(605.0, 680.5]    0.025500
(680.5, 756.0]    0.013648
Name: Sales, dtype: float64